### ISSUE TITLE
DeepLinking to Apps which are not Installed yet?

### ISSUE THREAD

**Issue by confile** [lucaslain/DeepLinking#2]
Is it possible to DeepLink to Apps which are not Installed yet?

**Comment by lucaslain** [comment]
@confile Hello! No, since the custom url scheme has not been registered yet. 

What you can do is this (from the app that you want to launch):

- test if the system can handle the application `UIApplication.sharedApplication().canOpenURL()`
- if not, show the app store in a modal view
- listen to the window being closed
- try to launch the scheme once it's closed
